In [217]:
import pandas as pd
import numpy as np

In [218]:
df1 = pd.read_csv("Dataset/dataset.csv")
df2 = pd.read_csv("Dataset/symptom_Description.csv")
df3 = pd.read_csv("Dataset/symptom_precaution.csv")

In [219]:
df1.head()


Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [220]:
df2.head(2)

Disease                                        Description
0  Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1        Malaria  An infectious disease caused by protozoan para...

In [221]:
merged_df = pd.merge(df1,df2, on= "Disease", how="inner")

In [222]:
merged_df.head(2)

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17                                        Description  
0        NaN        NaN  In humans, fungal infections occur when an inv...  
1        NaN        NaN  In humans, fungal infections occur when an inv...

In [223]:
final_df =pd.merge(merged_df,df3,on="Disease",how="inner")

In [224]:
final_df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

   ... Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  \
0  ...        NaN        NaN        NaN        NaN        NaN   
1  ...        NaN        NaN        NaN        NaN        NaN   
2  ...        NaN        NaN        NaN        NaN        NaN   
3  ...        NaN        NaN        NaN        NaN        NaN   
4  ...        NaN        NaN        NaN        NaN        NaN   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   
1  In humans, fungal infections occur when an inv...   bath twice   
2  In humans, fungal infections occur when an inv...   bath twice   
3  In humans, fungal infections occur when an inv...   bath twice   
4  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2            Precaution_3  \
0  use detol or neem in bathing water  keep infected area dry   
1  use detol or neem in bathing water  keep infected area dry   
2  use detol or neem in bathing water  keep infected area dry   
3  use detol or neem in bathing water  keep infected area dry   
4  use detol or neem in bathing water  keep infected area dry   

       Precaution_4  
0  use clean cloths  
1  use clean cloths  
2  use clean cloths  
3  use clean cloths  
4  use clean cloths  

[5 rows x 23 columns]

In [225]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Disease       4560 non-null   object
 1   Symptom_1     4560 non-null   object
 2   Symptom_2     4560 non-null   object
 3   Symptom_3     4560 non-null   object
 4   Symptom_4     4212 non-null   object
 5   Symptom_5     3432 non-null   object
 6   Symptom_6     2814 non-null   object
 7   Symptom_7     2148 non-null   object
 8   Symptom_8     1824 non-null   object
 9   Symptom_9     1572 non-null   object
 10  Symptom_10    1440 non-null   object
 11  Symptom_11    1194 non-null   object
 12  Symptom_12    744 non-null    object
 13  Symptom_13    504 non-null    object
 14  Symptom_14    306 non-null    object
 15  Symptom_15    240 non-null    object
 16  Symptom_16    192 non-null    object
 17  Symptom_17    72 non-null     object
 18  Description   4560 non-null   object
 19  Precau

In [226]:
final_df.isnull().sum()

Disease            0
Symptom_1          0
Symptom_2          0
Symptom_3          0
Symptom_4        348
Symptom_5       1128
Symptom_6       1746
Symptom_7       2412
Symptom_8       2736
Symptom_9       2988
Symptom_10      3120
Symptom_11      3366
Symptom_12      3816
Symptom_13      4056
Symptom_14      4254
Symptom_15      4320
Symptom_16      4368
Symptom_17      4488
Description        0
Precaution_1       0
Precaution_2       0
Precaution_3     120
Precaution_4     120
dtype: int64

In [227]:
final_df.describe

<bound method NDFrame.describe of                                       Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4555  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4556                                     Acne             skin_rash   
4557                  Urinary tract infection   burning_micturition   
4558                                Psoriasis             skin_rash   
4559                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   no

In [228]:
final_df.shape

(4560, 23)

In [229]:
final_df.head(1)

Disease Symptom_1   Symptom_2              Symptom_3  \
0  Fungal infection   itching   skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   

   ... Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  \
0  ...        NaN        NaN        NaN        NaN        NaN   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2            Precaution_3  \
0  use detol or neem in bathing water  keep infected area dry   

       Precaution_4  
0  use clean cloths  

[1 rows x 23 columns]

In [230]:
final_df.drop(columns=['Symptom_5','Symptom_6','Symptom_7','Symptom_8','Symptom_9','Symptom_10','Symptom_11','Symptom_12','Symptom_13','Symptom_14','Symptom_15','Symptom_16','Symptom_17'],axis=1,inplace=True)

In [231]:
final_df.head(2)

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   

              Symptom_4                                        Description  \
0   dischromic _patches  In humans, fungal infections occur when an inv...   
1                   NaN  In humans, fungal infections occur when an inv...   

  Precaution_1                        Precaution_2            Precaution_3  \
0   bath twice  use detol or neem in bathing water  keep infected area dry   
1   bath twice  use detol or neem in bathing water  keep infected area dry   

       Precaution_4  
0  use clean cloths  
1  use clean cloths

In [232]:
final_df.isnull().sum()

Disease           0
Symptom_1         0
Symptom_2         0
Symptom_3         0
Symptom_4       348
Description       0
Precaution_1      0
Precaution_2      0
Precaution_3    120
Precaution_4    120
dtype: int64

In [233]:
final_df['Symptom_4'].unique()

array([' dischromic _patches', nan, ' watering_from_eyes', ' vomiting',
       ' cough', ' nausea', ' loss_of_appetite', ' burning_micturition',
       ' spotting_ urination', ' passage_of_gases', ' abdominal_pain',
       ' extra_marital_contacts', ' diarrhoea', ' breathlessness',
       ' family_history', ' blurred_and_distorted_vision',
       ' excessive_hunger', ' dizziness', ' loss_of_balance',
       ' altered_sensorium', ' weight_loss', ' high_fever', ' sweating',
       ' headache', ' lethargy', ' fatigue', ' dark_urine',
       ' yellowish_skin', ' yellowing_of_eyes', ' swelling_of_stomach',
       ' distention_of_abdomen', ' chest_pain', ' obesity',
       ' swollen_legs', ' mood_swings', ' restlessness',
       ' hip_joint_pain', ' swelling_joints', ' movement_stiffness',
       ' painful_walking', ' spinning_movements', ' scurring',
       ' continuous_feel_of_urine', ' silver_like_dusting',
       ' small_dents_in_nails', ' red_sore_around_nose',
       ' yellow_crust_ooz

In [234]:
mode_value = final_df['Symptom_4'].mode()[0]

In [235]:
final_df['Symptom_4_Mode'] = final_df['Symptom_4'].fillna(mode_value) 

In [236]:
final_df.head(2)

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   

              Symptom_4                                        Description  \
0   dischromic _patches  In humans, fungal infections occur when an inv...   
1                   NaN  In humans, fungal infections occur when an inv...   

  Precaution_1                        Precaution_2            Precaution_3  \
0   bath twice  use detol or neem in bathing water  keep infected area dry   
1   bath twice  use detol or neem in bathing water  keep infected area dry   

       Precaution_4        Symptom_4_Mode  
0  use clean cloths   dischromic _patches  
1  use clean cloths            high_fever

In [237]:
final_df['Symptom_4_Mode'].isnull().sum()

np.int64(0)

In [238]:
final_df.drop(columns='Symptom_4',axis=1,inplace=True)

In [239]:
final_df.head(2)

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   
1  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2            Precaution_3  \
0  use detol or neem in bathing water  keep infected area dry   
1  use detol or neem in bathing water  keep infected area dry   

       Precaution_4        Symptom_4_Mode  
0  use clean cloths   dischromic _patches  
1  use clean cloths            high_fever

In [240]:
final_df.isnull().sum()

Disease             0
Symptom_1           0
Symptom_2           0
Symptom_3           0
Description         0
Precaution_1        0
Precaution_2        0
Precaution_3      120
Precaution_4      120
Symptom_4_Mode      0
dtype: int64

In [241]:
final_df['Precaution_3'].unique()

array(['keep infected area dry', nan, 'maintain healthy weight',
       'consult doctor', 'stop taking drug', 'eliminate milk', 'rest',
       'get away from trigger', 'use poloroid glasses in sun',
       'take otc pain reliver', 'exercise',
       'eat fruits and high fiberous food', 'avoid non veg food',
       'take vaccine', 'keep mosquitos away', 'avoid fatty spicy food',
       'eat healthy', 'medication', 'avoid cold food', 'keep calm',
       'use vein compression', 'use lemon balm', 'drink sugary drinks',
       'follow up', 'try acupuncture', 'avoid abrupt head movment',
       'drink plenty of water', 'drink cranberry juice',
       'remove scabs with wet compressed cloth'], dtype=object)

In [242]:
final_df['Precaution_3'].isnull().sum()

np.int64(120)

In [243]:
mode_value1 = final_df['Precaution_3'].mode()[0]

In [244]:
final_df['Precaution_3_Mode'] = final_df['Precaution_3'].fillna(mode_value1) 

In [245]:
final_df['Precaution_3_Mode'].isnull().sum()

np.int64(0)

In [246]:
final_df.drop(columns='Precaution_3',axis=1,inplace=True)

In [247]:
final_df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4555  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4556                                     Acne             skin_rash   
4557                  Urinary tract infection   burning_micturition   
4558                                Psoriasis             skin_rash   
4559                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3  \
0                 skin_rash   nodal_skin_eruptions   
1      nodal_skin_eruptions    dischromic _patches   
2      nodal_skin_eruptions    dischromic _patches   
3                 skin_rash    dischromic _patches   
4                 skin_rash   nodal_skin_eruptions   
...                     ...                    ...   
4555               headache                 nausea   
4556     pus_filled_pimples             blackheads   
4557     bladder_discomfort    foul_smell_of urine   
4558             joint_pain           skin_peeling   
4559             high_fever                blister   

                                            Description  \
0     In humans, fungal infections occur when an inv...   
1     In humans, fungal infections occur when an inv...   
2     In humans, fungal infections occur when an inv...   
3     In humans, fungal infections occur when an inv...   
4     In humans, fungal infections occur when an inv...   
...                                                 ...   
4555  Benign paroxysmal positional vertigo (BPPV) is...   
4556  Acne vulgaris is the formation of comedones, p...   
4557  Urinary tract infection: An infection of the k...   
4558  Psoriasis is a common skin disorder that forms...   
4559  Impetigo (im-puh-TIE-go) is a common and highl...   

                          Precaution_1                        Precaution_2  \
0                           bath twice  use detol or neem in bathing water   
1                           bath twice  use detol or neem in bathing water   
2                           bath twice  use detol or neem in bathing water   
3                           bath twice  use detol or neem in bathing water   
4                           bath twice  use detol or neem in bathing water   
...                                ...                                 ...   
4555                          lie down         avoid sudden change in body   
4556                        bath twice              avoid fatty spicy food   
4557             drink plenty of water           increase vitamin c intake   
4558  wash hands with warm soapy water        stop bleeding using pressure   
4559  soak affected area in warm water                     use antibiotics   

                 Precaution_4             Symptom_4_Mode  \
0            use clean cloths        dischromic _patches   
1            use clean cloths                 high_fever   
2            use clean cloths                 high_fever   
3            use clean cloths                 high_fever   
4            use clean cloths                 high_fever   
...                       ...                        ...   
4555                    relax         spinning_movements   
4556  avoid too many products                   scurring   
4557          take probiotics   continuous_feel_of_urine   
4558               salt baths        silver_like_dusting   
4559           consult doctor       red_sore_around_nose   

                           Precaution_3_Mode  
0                     keep infected area dry  
1                     keep infected area dry  
2                     keep i

In [248]:
final_df['Precaution_4'].isnull().sum()

np.int64(120)

In [249]:
mode_value2 = final_df['Precaution_4'].mode()[0]

In [250]:
final_df['Precaution_4_Mode'] = final_df['Precaution_4'].fillna(mode_value2) 

In [251]:
final_df['Precaution_4_Mode'].isnull().sum()

np.int64(0)

In [252]:
final_df.drop(columns='Precaution_4',axis=1,inplace=True)

In [253]:
final_df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4555  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4556                                     Acne             skin_rash   
4557                  Urinary tract infection   burning_micturition   
4558                                Psoriasis             skin_rash   
4559                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3  \
0                 skin_rash   nodal_skin_eruptions   
1      nodal_skin_eruptions    dischromic _patches   
2      nodal_skin_eruptions    dischromic _patches   
3                 skin_rash    dischromic _patches   
4                 skin_rash   nodal_skin_eruptions   
...                     ...                    ...   
4555               headache                 nausea   
4556     pus_filled_pimples             blackheads   
4557     bladder_discomfort    foul_smell_of urine   
4558             joint_pain           skin_peeling   
4559             high_fever                blister   

                                            Description  \
0     In humans, fungal infections occur when an inv...   
1     In humans, fungal infections occur when an inv...   
2     In humans, fungal infections occur when an inv...   
3     In humans, fungal infections occur when an inv...   
4     In humans, fungal infections occur when an inv...   
...                                                 ...   
4555  Benign paroxysmal positional vertigo (BPPV) is...   
4556  Acne vulgaris is the formation of comedones, p...   
4557  Urinary tract infection: An infection of the k...   
4558  Psoriasis is a common skin disorder that forms...   
4559  Impetigo (im-puh-TIE-go) is a common and highl...   

                          Precaution_1                        Precaution_2  \
0                           bath twice  use detol or neem in bathing water   
1                           bath twice  use detol or neem in bathing water   
2                           bath twice  use detol or neem in bathing water   
3                           bath twice  use detol or neem in bathing water   
4                           bath twice  use detol or neem in bathing water   
...                                ...                                 ...   
4555                          lie down         avoid sudden change in body   
4556                        bath twice              avoid fatty spicy food   
4557             drink plenty of water           increase vitamin c intake   
4558  wash hands with warm soapy water        stop bleeding using pressure   
4559  soak affected area in warm water                     use antibiotics   

                 Symptom_4_Mode                       Precaution_3_Mode  \
0           dischromic _patches                  keep infected area dry   
1                    high_fever                  keep infected area dry   
2                    high_fever                  keep infected area dry   
3                    high_fever                  keep infected area dry   
4                    high_fever                  keep infected area dry   
...                         ...                                     ...   
4555         spinning_movements               avoid abrupt head movment   
4556                   scurring                   drink plenty of water   
4557   continuous_feel_of_urine                   drink cranberry juice   
4558        silver_like_dusting                          consult doctor   
4559       red_sore_around_nose  remove scabs with wet compressed

In [254]:
final_df.isnull().sum()

Disease              0
Symptom_1            0
Symptom_2            0
Symptom_3            0
Description          0
Precaution_1         0
Precaution_2         0
Symptom_4_Mode       0
Precaution_3_Mode    0
Precaution_4_Mode    0
dtype: int64

In [255]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Disease            4560 non-null   object
 1   Symptom_1          4560 non-null   object
 2   Symptom_2          4560 non-null   object
 3   Symptom_3          4560 non-null   object
 4   Description        4560 non-null   object
 5   Precaution_1       4560 non-null   object
 6   Precaution_2       4560 non-null   object
 7   Symptom_4_Mode     4560 non-null   object
 8   Precaution_3_Mode  4560 non-null   object
 9   Precaution_4_Mode  4560 non-null   object
dtypes: object(10)
memory usage: 356.4+ KB


In [256]:
final_df.describe()

Disease  Symptom_1  Symptom_2 Symptom_3  \
count               4560       4560       4560      4560   
unique                38         30         43        51   
top     Fungal infection   vomiting   vomiting   fatigue   
freq                 120        822        870       726   

                                              Description  \
count                                                4560   
unique                                                 38   
top     In humans, fungal infections occur when an inv...   
freq                                                  120   

                    Precaution_1              Precaution_2 Symptom_4_Mode  \
count                       4560                      4560           4560   
unique                        31                        32             46   
top     Consult nearest hospital  consult nearest hospital     high_fever   
freq                         360                       240            726   

       Precaution_3_Mode Precaution_4_Mode  
count               4560              4560  
unique                28                23  
top       consult doctor        medication  
freq                 720               840

In [257]:
final_df.tail(4)

Disease             Symptom_1            Symptom_2  \
4556                     Acne             skin_rash   pus_filled_pimples   
4557  Urinary tract infection   burning_micturition   bladder_discomfort   
4558                Psoriasis             skin_rash           joint_pain   
4559                 Impetigo             skin_rash           high_fever   

                 Symptom_3                                        Description  \
4556            blackheads  Acne vulgaris is the formation of comedones, p...   
4557   foul_smell_of urine  Urinary tract infection: An infection of the k...   
4558          skin_peeling  Psoriasis is a common skin disorder that forms...   
4559               blister  Impetigo (im-puh-TIE-go) is a common and highl...   

                          Precaution_1                  Precaution_2  \
4556                        bath twice        avoid fatty spicy food   
4557             drink plenty of water     increase vitamin c intake   
4558  wash hands with warm soapy water  stop bleeding using pressure   
4559  soak affected area in warm water               use antibiotics   

                 Symptom_4_Mode                       Precaution_3_Mode  \
4556                   scurring                   drink plenty of water   
4557   continuous_feel_of_urine                   drink cranberry juice   
4558        silver_like_dusting                          consult doctor   
4559       red_sore_around_nose  remove scabs with wet compressed cloth   

            Precaution_4_Mode  
4556  avoid too many products  
4557          take probiotics  
4558               salt baths  
4559           consult doctor

In [258]:
final_df['Disease'].value_counts()

Disease
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Gastroenteritis                            120
Bronchial Asthma                           120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepat

In [259]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [260]:
label_encoder.fit_transform(final_df[['Disease']])

d:\Python\Project\HealthCare\venv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([13, 13, 13, ..., 35, 32, 24], shape=(4560,))

In [261]:
final_df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4555  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4556                                     Acne             skin_rash   
4557                  Urinary tract infection   burning_micturition   
4558                                Psoriasis             skin_rash   
4559                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3  \
0                 skin_rash   nodal_skin_eruptions   
1      nodal_skin_eruptions    dischromic _patches   
2      nodal_skin_eruptions    dischromic _patches   
3                 skin_rash    dischromic _patches   
4                 skin_rash   nodal_skin_eruptions   
...                     ...                    ...   
4555               headache                 nausea   
4556     pus_filled_pimples             blackheads   
4557     bladder_discomfort    foul_smell_of urine   
4558             joint_pain           skin_peeling   
4559             high_fever                blister   

                                            Description  \
0     In humans, fungal infections occur when an inv...   
1     In humans, fungal infections occur when an inv...   
2     In humans, fungal infections occur when an inv...   
3     In humans, fungal infections occur when an inv...   
4     In humans, fungal infections occur when an inv...   
...                                                 ...   
4555  Benign paroxysmal positional vertigo (BPPV) is...   
4556  Acne vulgaris is the formation of comedones, p...   
4557  Urinary tract infection: An infection of the k...   
4558  Psoriasis is a common skin disorder that forms...   
4559  Impetigo (im-puh-TIE-go) is a common and highl...   

                          Precaution_1                        Precaution_2  \
0                           bath twice  use detol or neem in bathing water   
1                           bath twice  use detol or neem in bathing water   
2                           bath twice  use detol or neem in bathing water   
3                           bath twice  use detol or neem in bathing water   
4                           bath twice  use detol or neem in bathing water   
...                                ...                                 ...   
4555                          lie down         avoid sudden change in body   
4556                        bath twice              avoid fatty spicy food   
4557             drink plenty of water           increase vitamin c intake   
4558  wash hands with warm soapy water        stop bleeding using pressure   
4559  soak affected area in warm water                     use antibiotics   

                 Symptom_4_Mode                       Precaution_3_Mode  \
0           dischromic _patches                  keep infected area dry   
1                    high_fever                  keep infected area dry   
2                    high_fever                  keep infected area dry   
3                    high_fever                  keep infected area dry   
4                    high_fever                  keep infected area dry   
...                         ...                                     ...   
4555         spinning_movements               avoid abrupt head movment   
4556                   scurring                   drink plenty of water   
4557   continuous_feel_of_urine                   drink cranberry juice   
4558        silver_like_dusting                          consult doctor   
4559       red_sore_around_nose  remove scabs with wet compressed

In [262]:
label_encoder.transform([['Fungal infection']])

d:\Python\Project\HealthCare\venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([13])

In [263]:
final_df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4555  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4556                                     Acne             skin_rash   
4557                  Urinary tract infection   burning_micturition   
4558                                Psoriasis             skin_rash   
4559                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3  \
0                 skin_rash   nodal_skin_eruptions   
1      nodal_skin_eruptions    dischromic _patches   
2      nodal_skin_eruptions    dischromic _patches   
3                 skin_rash    dischromic _patches   
4                 skin_rash   nodal_skin_eruptions   
...                     ...                    ...   
4555               headache                 nausea   
4556     pus_filled_pimples             blackheads   
4557     bladder_discomfort    foul_smell_of urine   
4558             joint_pain           skin_peeling   
4559             high_fever                blister   

                                            Description  \
0     In humans, fungal infections occur when an inv...   
1     In humans, fungal infections occur when an inv...   
2     In humans, fungal infections occur when an inv...   
3     In humans, fungal infections occur when an inv...   
4     In humans, fungal infections occur when an inv...   
...                                                 ...   
4555  Benign paroxysmal positional vertigo (BPPV) is...   
4556  Acne vulgaris is the formation of comedones, p...   
4557  Urinary tract infection: An infection of the k...   
4558  Psoriasis is a common skin disorder that forms...   
4559  Impetigo (im-puh-TIE-go) is a common and highl...   

                          Precaution_1                        Precaution_2  \
0                           bath twice  use detol or neem in bathing water   
1                           bath twice  use detol or neem in bathing water   
2                           bath twice  use detol or neem in bathing water   
3                           bath twice  use detol or neem in bathing water   
4                           bath twice  use detol or neem in bathing water   
...                                ...                                 ...   
4555                          lie down         avoid sudden change in body   
4556                        bath twice              avoid fatty spicy food   
4557             drink plenty of water           increase vitamin c intake   
4558  wash hands with warm soapy water        stop bleeding using pressure   
4559  soak affected area in warm water                     use antibiotics   

                 Symptom_4_Mode                       Precaution_3_Mode  \
0           dischromic _patches                  keep infected area dry   
1                    high_fever                  keep infected area dry   
2                    high_fever                  keep infected area dry   
3                    high_fever                  keep infected area dry   
4                    high_fever                  keep infected area dry   
...                         ...                                     ...   
4555         spinning_movements               avoid abrupt head movment   
4556                   scurring                   drink plenty of water   
4557   continuous_feel_of_urine                   drink cranberry juice   
4558        silver_like_dusting                          consult doctor   
4559       red_sore_around_nose  remove scabs with wet compressed

In [264]:
final_df['Disease_Encoded']=label_encoder.fit_transform(final_df['Disease'])

In [265]:
final_df.head(1)

Disease Symptom_1   Symptom_2              Symptom_3  \
0  Fungal infection   itching   skin_rash   nodal_skin_eruptions   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  
0  keep infected area dry  use clean cloths               13

In [266]:
final_df.drop('Disease',axis=1,inplace=True)

In [267]:
final_df.head(1)

Symptom_1   Symptom_2              Symptom_3  \
0   itching   skin_rash   nodal_skin_eruptions   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  
0  keep infected area dry  use clean cloths               13

In [268]:
final_df['Sympton_1_Encoded']=label_encoder.fit_transform(final_df['Symptom_1'])

In [269]:
final_df.head(1)

Symptom_1   Symptom_2              Symptom_3  \
0   itching   skin_rash   nodal_skin_eruptions   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  
0                 29

In [270]:
final_df.drop('Symptom_1',axis=1,inplace=True)

In [271]:
final_df.head(1)

Symptom_2              Symptom_3  \
0   skin_rash   nodal_skin_eruptions   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  
0                 29

In [272]:
final_df['Sympton_2_Encoded']=label_encoder.fit_transform(final_df['Symptom_2'])

In [273]:
final_df.head(1)

Symptom_2              Symptom_3  \
0   skin_rash   nodal_skin_eruptions   

                                         Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  
0                 29                 30

In [274]:
final_df.drop('Symptom_2',axis=1,inplace=True)

In [275]:
final_df.head(1)

Symptom_3                                        Description  \
0   nodal_skin_eruptions  In humans, fungal infections occur when an inv...   

  Precaution_1                        Precaution_2        Symptom_4_Mode  \
0   bath twice  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  
0                 29                 30

In [276]:
final_df['Sympton_3_Encoded']=label_encoder.fit_transform(final_df['Symptom_3'])
final_df.head(1)

Symptom_3                                        Description  \
0   nodal_skin_eruptions  In humans, fungal infections occur when an inv...   

  Precaution_1                        Precaution_2        Symptom_4_Mode  \
0   bath twice  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  
0                 29                 30                 33

In [277]:
final_df.drop('Symptom_3',axis=1,inplace=True)

In [278]:
final_df.head(1)


Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  
0                 29                 30                 33

In [279]:
final_df['Description_Encoded']=label_encoder.fit_transform(final_df['Description'])
final_df.head(1)

Description Precaution_1  \
0  In humans, fungal infections occur when an inv...   bath twice   

                         Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  
0                   25

In [280]:
final_df.drop('Description',axis=1,inplace=True)


In [281]:
final_df.head(1)

Precaution_1                        Precaution_2        Symptom_4_Mode  \
0   bath twice  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  
0                   25

In [282]:
final_df['Precaution_1_Encoded']=label_encoder.fit_transform(final_df['Precaution_1'])
final_df.head(1)


Precaution_1                        Precaution_2        Symptom_4_Mode  \
0   bath twice  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  
0                   25                     5

In [283]:
final_df.drop('Precaution_1',axis=1,inplace=True)
final_df.head(1)


Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  
0                   25                     5

In [284]:
final_df['Precaution_2_Encoded']=label_encoder.fit_transform(final_df['Precaution_2'])
final_df.head(1)

Precaution_2        Symptom_4_Mode  \
0  use detol or neem in bathing water   dischromic _patches   

        Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  
0                   25                     5                    26

In [285]:
final_df.drop('Precaution_2',axis=1,inplace=True)
final_df.head(1)


Symptom_4_Mode       Precaution_3_Mode Precaution_4_Mode  \
0   dischromic _patches  keep infected area dry  use clean cloths   

   Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0               13                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  
0                   25                     5                    26

In [286]:
final_df['Symptom_4_Mode_Encoded']=label_encoder.fit_transform(final_df['Symptom_4_Mode'])
final_df.head(1)

Symptom_4_Mode       Precaution_3_Mode Precaution_4_Mode  \
0   dischromic _patches  keep infected area dry  use clean cloths   

   Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0               13                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  \
0                   25                     5                    26   

   Symptom_4_Mode_Encoded  
0                      10

In [287]:
final_df.drop('Symptom_4_Mode',axis=1,inplace=True)
final_df.head(1)

Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  \
0                   25                     5                    26   

   Symptom_4_Mode_Encoded  
0                      10

In [288]:
final_df['Precaution_3_Mode_Encoded']=label_encoder.fit_transform(final_df['Precaution_3_Mode'])
final_df.head(1)

Precaution_3_Mode Precaution_4_Mode  Disease_Encoded  \
0  keep infected area dry  use clean cloths               13   

   Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  \
0                   25                     5                    26   

   Symptom_4_Mode_Encoded  Precaution_3_Mode_Encoded  
0                      10                         15

In [289]:
final_df.drop('Precaution_3_Mode',axis=1,inplace=True)
final_df.head(1)

Precaution_4_Mode  Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  \
0  use clean cloths               13                 29                 30   

   Sympton_3_Encoded  Description_Encoded  Precaution_1_Encoded  \
0                 33                   25                     5   

   Precaution_2_Encoded  Symptom_4_Mode_Encoded  Precaution_3_Mode_Encoded  
0                    26                      10                         15

In [290]:
final_df['Precaution_4_Mode_Encoded']=label_encoder.fit_transform(final_df['Precaution_4_Mode'])
final_df.head(1)

Precaution_4_Mode  Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  \
0  use clean cloths               13                 29                 30   

   Sympton_3_Encoded  Description_Encoded  Precaution_1_Encoded  \
0                 33                   25                     5   

   Precaution_2_Encoded  Symptom_4_Mode_Encoded  Precaution_3_Mode_Encoded  \
0                    26                      10                         15   

   Precaution_4_Mode_Encoded  
0                         21

In [291]:
final_df.drop('Precaution_4_Mode',axis=1,inplace=True)
final_df.head(1)

Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0               13                 29                 30                 33   

   Description_Encoded  Precaution_1_Encoded  Precaution_2_Encoded  \
0                   25                     5                    26   

   Symptom_4_Mode_Encoded  Precaution_3_Mode_Encoded  \
0                      10                         15   

   Precaution_4_Mode_Encoded  
0                         21

In [292]:
final_df

Disease_Encoded  Sympton_1_Encoded  Sympton_2_Encoded  \
0                  13                 29                 30   
1                  13                 21                 25   
2                  13                 29                 25   
3                  13                 29                 30   
4                  13                 29                 30   
...               ...                ...                ...   
4555                0                 25                 15   
4556                2                 21                 27   
4557               35                  4                  4   
4558               32                 21                 18   
4559               24                 21                 16   

      Sympton_3_Encoded  Description_Encoded  Precaution_1_Encoded  \
0                    33                   25                     5   
1                    17                   25                     5   
2                    17                   25                     5   
3                    17                   25                     5   
4                    33                   25                     5   
...                 ...                  ...                   ...   
4555                 31                   12                    17   
4556                  3                    4                     5   
4557                 21                   35                    12   
4558                 39                   31                    30   
4559                  4                   24                    23   

      Precaution_2_Encoded  Symptom_4_Mode_Encoded  Precaution_3_Mode_Encoded  \
0                       26                      10                         15   
1                       26                      18                         15   
2                       26                      18                         15   
3                       26                      18                         15   
4                       26                      18                         15   
...                    ...                     ...                        ...   
4555                     5                      34                          0   
4556                     2                      31                          6   
4557                    16                       6                          5   
4558                    21                      32                          4   
4559                    25                      29                         19   

      Precaution_4_Mode_Encoded  
0                            21  
1                            21  
2                            21  
3                            21  
4                            21  
...                         ...  
4555                         15  
4556                          1  
4557                         19  
4558                         17  
4559                          2  

[4560 rows x 10 columns]

In [293]:
from sklearn.model_selection import train_test_split

In [294]:
X=final_df.drop(['Disease_Encoded','Precaution_1_Encoded','Precaution_2_Encoded','Precaution_3_Mode_Encoded','Precaution_4_Mode_Encoded','Description_Encoded'],axis=1)
y=final_df['Disease_Encoded']

In [295]:
X

Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                    29                 30                 33   
1                    21                 25                 17   
2                    29                 25                 17   
3                    29                 30                 17   
4                    29                 30                 33   
...                 ...                ...                ...   
4555                 25                 15                 31   
4556                 21                 27                  3   
4557                  4                  4                 21   
4558                 21                 18                 39   
4559                 21                 16                  4   

      Symptom_4_Mode_Encoded  
0                         10  
1                         18  
2                         18  
3                         18  
4                         18  
...                      ...  
4555                      34  
4556                      31  
4557                       6  
4558                      32  
4559                      29  

[4560 rows x 4 columns]

In [296]:
X.head(1)

Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
0                 29                 30                 33   

   Symptom_4_Mode_Encoded  
0                      10

In [297]:
y.head(4)

0    13
1    13
2    13
3    13
Name: Disease_Encoded, dtype: int64

In [298]:
X.shape

(4560, 4)

In [299]:
y.shape

(4560,)

In [300]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [301]:
X_train

Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
2413                  9                 42                 31   
1721                 25                 13                 50   
3291                  5                 37                 20   
1412                  8                  7                 34   
4412                 29                 30                 41   
...                 ...                ...                ...   
4426                 29                 13                 27   
466                   9                 10                 23   
3092                 29                 30                 20   
3772                  1                 38                 32   
860                   1                 38                 32   

      Symptom_4_Mode_Encoded  
2413                      21  
1721                       8  
3291                      42  
1412                      39  
4412                       4  
...                      ...  
4426                      45  
466                        3  
3092                      20  
3772                      12  
860                       12  

[3648 rows x 4 columns]

In [302]:
X_test

Sympton_1_Encoded  Sympton_2_Encoded  Sympton_3_Encoded  \
471                  12                 15                  5   
2646                  6                  8                 20   
23                   23                  1                 45   
3477                  9                 42                 31   
135                   5                 37                 42   
...                 ...                ...                ...   
2115                 13                 37                 23   
4348                  5                 37                 20   
408                  23                  1                 46   
170                  13                 37                 50   
540                   5                 37                 20   

      Symptom_4_Mode_Encoded  
471                       13  
2646                       7  
23                         7  
3477                      21  
135                       17  
...                      ...  
2115                      45  
4348                      18  
408                        7  
170                        8  
540                       18  

[912 rows x 4 columns]

In [303]:
y_train

2413    18
1721    19
3291    33
1412    36
4412    12
        ..
4426    17
466      6
3092     8
3772     7
860      7
Name: Disease_Encoded, Length: 3648, dtype: int64

In [304]:
y_test

471     27
2646    10
23      14
3477    18
135     26
        ..
2115    20
4348    34
408     14
170     37
540     34
Name: Disease_Encoded, Length: 912, dtype: int64

In [305]:
from sklearn.preprocessing import MinMaxScaler

ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [306]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(X_train)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)


In [307]:
X_train

array([[-0.78853891,  1.49893403,  0.39914332, -0.09785698],
       [ 0.92104578, -0.88379269,  1.74979616, -1.0956573 ],
       [-1.21593508,  1.08811908, -0.38281358,  1.51397431],
       ...,
       [ 1.34844195,  0.51297814, -0.38281358, -0.17461085],
       [-1.64333125,  1.17028207,  0.47023032, -0.78864182],
       [-1.64333125,  1.17028207,  0.47023032, -0.78864182]],
      shape=(3648, 4))

In [308]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}

for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred= model.predict(X_test)
    print(f"{name} with accuracy: {accuracy_score(y_test,y_pred)}")
    print("Confusion Matrix: ",confusion_matrix(y_test,y_pred))
    print("----------------------------------------------------------------------")

Logistic Regression with accuracy: 0.7697368421052632
Confusion Matrix:  [[20  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 20 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 18]]
----------------------------------------------------------------------
Naive Bayes with accuracy: 0.7609649122807017
Confusion Matrix:  [[18  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 25 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 21]]
----------------------------------------------------------------------
Support Vector Machine with accuracy: 0.9375
Confusion Matrix:  [[21  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 32 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 23]]
----------------------------------------------------------------------
K-Nearest Neighbors with accuracy: 0.981359649122807
Confusion Matrix:  [[21  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0

In [309]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9945175438596491

In [310]:
def recommendation(Symptom_1,Symptom_2,Symptom_3,Symptom_4):
    features = np.array([[Symptom_1,Symptom_2,Symptom_3,Symptom_4]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0]

In [311]:
final_df['Disease_Encoded'].value_counts().sum()

np.int64(4560)

In [312]:
import pickle

pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))
pickle.dump(sc,open("standardscaler.pkl","wb"))
pickle.dump(label_encoder,open("label_encoder.pkl","wb"))


In [326]:
Symptom_1 = "itching"
Symptom_2 = " skin_rash"
Symptom_3 = " nodal_skin_eruptions"
Symptom_4= " dischromic _patches"

input_data = np.array([Symptom_1,Symptom_2,Symptom_3,Symptom_4]).reshape(1,-1)

predict = recommendation(Symptom_1,Symptom_2,Symptom_3,Symptom_4)

disease= {
        1: "Drug Reaction", 2:"Malaria", 3:"Allergy", 4:"Hypothyroidism", 5:"Psoriasis", 6:"GERD",
        7:"Chronic cholestasis", 8:"hepatitis A", 9:"Osteoarthristis", 10:"(vertigo) Paroymsal  Positional Vertig",
        11:"Hypoglycemia", 12:"Acne", 13:"Diabetes", 14:"Impetigo", 15:"Hypertension", 16:"Peptic ulcer diseae",
        17:"Dimorphic hemorrhoids(piles)", 18:"Common Cold", 19:"Chicken pox", 20:"Cervical spondylosis", 21:"Hyperthyroidism",
        22: "Urinary tract infection", 23:"Varicose veins", 24:"AIDS", 25:"Paralysis (brain hemorrhage)", 26:"Typhoid",
        27:"Hepatitis B", 28:"Fungal infection", 29:"Hepatitis C", 30:"Migraine", 31:"Bronchial Asthma", 32: "Alcoholic hepatitis",
        33:"Jaundice", 34:"Hepatitis E", 35:"Dengue", 36:"Hepatitis D", 37:"Heart attack", 38:"Pneumonia", 39:"Arthritis",
        40:"Gastroenteritis", 41:"Tuberculosis"
    }

if predict in disease:
    disease_on = disease[predict]
    print("{} is a the disease You have".format(disease_on))
else:
    print("Sorry no disease is matching your symptoms")

Common Cold is a the disease You have
